import type { Metadata } from "next";
import {Cormorant_Garamond, Playfair_Display, Lato} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";


const geistGaramond = Cormorant_Garamond({
  variable: "--font-cormorand-garamond",
  subsets: ["latin"],
});

const geistPlayfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

const geistLato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: "300"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistGaramond.variable} ${geistPlayfairDisplay.variable} ${geistLato.variable}antialiased`}
      >
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
